CFLAGS=-Wall -g
ex5:ex5.c
	cc -g -Wall ex5.c -o ex5
ex6:ex6.c
	cc -g -Wall ex6.c -o ex6
ex7:ex7.c
	cc -g -Wall ex7.c -o ex7
ex8:ex8.c
	cc -g -Wall ex8.c -o ex8
ex9:ex9.c
	cc -g -Wall ex9.c -o ex9
ex10:ex10.c
	cc -g -Wall ex10.c -o ex10
ex11:ex11.c
	cc -g -Wall ex11.c -o ex11
ex12:ex12.c
	cc -g -Wall ex12.c -o ex12
ex13:ex13.c
	cc -g -Wall ex13.c -o ex13
ex14:ex14.c
	cc -g -Wall ex14.c -o ex14
ex15:ex15.c
	cc -g -Wall ex15.c -o ex15
ex16:ex16.c
	cc -g -Wall ex16.c -o ex16
ex17:ex17.c
	cc -g -Wall ex17.c -o ex17
test:test.c
	cc -g -Wall test.c -o test
ex18:ex18.c
	cc -g -Wall ex18.c -o ex18
clean:
	rm -f ex5 ex6 ex7 ex8 ex9 ex10 ex11 ex12 ex13 ex14 ex15 ex16 ex17 test ex18